apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  secretkey: VkpFWWVSMGFLTlJHWW9oL2RXYTFEZVdESVNLQXpVaFR3UWxia29RQ0p2NHpNNVhNdE9RMEVHYkFwdUIvYVA3Vg==
  # username: <base64_encoded_username>
  # password: <base64_encoded_password>