apiVersion: apps/v1 #version of the API to use
kind: Deployment #what kind of object we're deploying
metadata: #information about our object we're deploying
  name: user-api-deployment #ame of the deployment
  labels: #a labels on the deployments created
    owner: lehel
spec: #specifications for our object
  replicas: 1 #the number of pods that should always be running
  selector: #which pods the replica set should be responsible for
    matchLabels:
      app: user-api #any pods with labels matching this I'm responsible for
  template: #the pod template that gets deployed
    metadata:
      labels: #labels on the replica set and pods created
        app: user-api
    spec:
      containers:
      - name: nginx-container #the name of the container within the pod

        #which container image should be pulled
        image: registry.digitalocean.com/lehel/user-api:20240606
        imagePullPolicy: Always
        ports:
        - containerPort: 80 #the port of the container within the pod
          protocol: TCP

        env:
        - name: MONGO_URL
          # value: "mongodb://mongouser:mongouser@mongo-service:27017/test?replicaSet=MainRepSet"
          # value: "mongodb://mongouser:mongouser@mongo-service:27017/authSource=test"
          # value: "mongodb://mongouser:mongouser@mongo-statefulset-0.mongo-service:27017"
          # value: "mongodb://mongouser:mongouser@mongo-service:27017/users?authSource=microservice1"
          # value: "mongodb://mongouser:mongouser@mongo-service:27017/microservice1?replicaSet=MainRepSet"
          value: "mongodb://mongouser:mongouser@mongo-service:27017/"
        - name: KAFKA_URI
          valueFrom:
            secretKeyRef:
              name: kafka-user-secret
              key: kafka-uri
        - name: KAFKA_USERNAME
          valueFrom:
            secretKeyRef:
              name: kafka-user-secret
              key: kafka-username
        - name: KAFKA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-user-secret
              key: kafka-password


      imagePullSecrets:
        - name: lehel-registry-secret